spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/timetalk_api
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: timetalk-api

security:
  jwt:
    key:
      private: 2dd57dfe27e671d7fad1d9517900518607dfb1d0a4718105b2e69986349d0a83
    user:
      generator: AUTH0JWT-BACKEND