spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: timetalk-api

security:
  jwt:
    key:
      private: 2dd57dfe27e671d7fad1d9517900518607dfb1d0a4718105b2e69986349d0a83
    user:
      generator: AUTH0JWT-BACKEND